### ISSUE TITLE
조회 결과 리스트 UI 짤림 현상

### ISSUE THREAD

**Issue by as-scrap** [sunhwa508/ggdata#2]
### 현상
- 브라우저 사이즈 700px 이하 발생
- 조회 결과의 마지막 리스트 아이템이 정상적으로 노출 되지 않음.

### 참고
![image](https://user-images.githubusercontent.com/39152030/83349843-ba92bf00-a372-11ea-9714-93a5380a340d.png)

cc. @sunhwa508

**Comment by sunhwa508** [comment]
빠르게 수정조치 취하겠습니다, : ) 보고 감사드립니다.

**Comment by as-scrap** [comment]
> 빠르게 수정조치 취하겠습니다, : ) 보고 감사드립니다.

작업 절차는 네이버 쪽지로 전달 드렸습니다.

**Comment by sunhwa508** [comment]
수정 완료 하였습니다, page number과 버튼도 추가 업로드 하였어요 👍
